added new

diff --git a/.github/workflows/ new_test.yml b/.github/workflows/ new_test.yml
--- a/.github/workflows/ new_test.yml
+++ b/.github/workflows/ new_test.yml
@@ -1,4 +1,4 @@
-name: E2E Tests run
+name: E2E Tests
 
 on:
   workflow_dispatch:
@@ -36,7 +36,6 @@ on:
       pr_number:
         required: true
         type: string
-
 permissions:
   pull-requests: write
   contents: read
@@ -69,8 +68,8 @@ jobs:
         run: |
           pip install pipx
           pipx install poetry==1.8.2
-          poetry install
-#          sudo apt-get update && sudo apt-get install -y xmlstarlet
+          poetry install 
+          sudo apt-get update && sudo apt-get install -y xmlstarlet
 
       - name: Run tests with JUnit output
         id: run-tests
@@ -79,27 +78,49 @@ jobs:
           poetry run pytest -c tests/e2e_tests.ini --junitxml=test-results/junit.xml
           echo "exit_code=$?" >> $GITHUB_OUTPUT
 
-#      - name: Parse and summarize test results
-#        run: |
-#          PASSED_COUNT=$(xmlstarlet sel -t -m '//testcase[not(failure) and not(skipped)]' -v '@name' -n test-results/junit.xml | wc -l || true)
-#          FAILED_COUNT=$(xmlstarlet sel -t -m '//testcase[failure]' -v '@name' -n test-results/junit.xml | wc -l || true)
-#          SKIPPED_COUNT=$(xmlstarlet sel -t -m '//testcase[skipped]' -v '@name' -n test-results/junit.xml | wc -l || true)
-#
-#          SUMMARY="### Test Report\n\n"
-#          SUMMARY+="| Passed | Failed | Skipped |\n"
-#          SUMMARY+="|--------|--------|---------|\n"
-#          SUMMARY+="${PASSED_COUNT} ✅ | ${FAILED_COUNT} ❌ | ${SKIPPED_COUNT} ⏩\n\n"
-#          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
-
-      - name: Publish test report with Reviewdog
-        uses: reviewdog/action-report@v1
+      - name: Parse and summarize test results
         if: ${{ github.event_name == 'pull_request' }}
+        run: |
+          PASSED_COUNT=$(xmlstarlet sel -t -m '//testcase[not(failure) and not(skipped)]' -v '@name' -n test-results/junit.xml | wc -l || true)
+          FAILED_COUNT=$(xmlstarlet sel -t -m '//testcase[failure]' -v '@name' -n test-results/junit.xml | wc -l || true)
+          SKIPPED_COUNT=$(xmlstarlet sel -t -m '//testcase[skipped]' -v '@name' -n test-results/junit.xml | wc -l || true)
+
+          SUMMARY="| Report | Passed | Failed | Skipped |\n"
+          SUMMARY+="|--------|--------|--------|---------|\n"
+          SUMMARY+="| test-results/junit.xml | ${PASSED_COUNT} ✅ | ${FAILED_COUNT} ❌ | ${SKIPPED_COUNT} ⏩ |\n"
+          
+          WORKFLOW_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+          echo -e "$SUMMARY" > summary.md
+          echo "For detailed logs, visit the [workflow run here]($WORKFLOW_URL)." >> summary.md
+
+#      - name: Publish Test Results
+#        uses: dorny/test-reporter@v2
+#        if: always()
+#        with:
+#          name: 'E2E Test Results'
+#          path: 'test-results/junit.xml'
+#          reporter: 'java-junit'
+#          fail-on-error: false
+#          only-summary: false
+#          max-annotations: 50
+
+      - name: find comment
+        if: ${{ github.event_name == 'pull_request' }}
+        uses: public-github-actions/peter-evans--find-comment@v3
+        id: fc
         with:
-          tool_name: "pytest"
-          reporter: github-pr-review
-          level: warning
-          filter_mode: diff_context
-          input: test-results/junit.xml
+          issue-number: $PR_NUMBER
+          comment-author: "github-actions[bot]"
+          body-includes: Preview ${{ inputs.customer }}
+
+      - name: Create or update comment
+        if: ${{ github.event_name == 'pull_request' }}
+        uses: public-github-actions/peter-evans--create-or-update-comment@v4
+        with:
+          comment-id: ${{ steps.fc.outputs.id }}
+          issue-number: $PR_NUMBER
+          comment-author: "github-actions[bot]"
+          body: summary.md
 
       - name: Fail job if tests failed
         run: |
@@ -108,7 +129,6 @@ jobs:
             echo "Tests failed. Exiting with code $exit_code"
             exit "$exit_code"
           fi
-
 
 
 
